export const BOSSES = {
  boss_age1_trex: {
    id: 'boss_age1_trex',
    name: 'Apex Tyrannosaurus Rex',
    nameVi: 'Khủng Long Bạo Chúa Apex T-Rex',
    title: 'Chúa Tể Kỷ Jura',
    ageId: 1,
    hp: 4200,
    physicalArmor: 25,
    magicResistance: 15,
    tenacity: 0.30,
    hpRegen: 8.0,
    damage: 95,
    attackRange: 60,
    attackCooldown: 1.4,
    moveSpeed: 38,
    width: 140,
    height: 120,
    xpReward: 3000,
    killBounty: 800,
    specialSkillId: 'SKILL_BOSS_PRIMAL_ROAR_801',
    specialCooldown: 12,
    color: '#15803d',
    accentColor: '#ef4444',
    descriptionVi: 'Quái thú tiền sử khổng lồ với tiếng gầm làm rung chuyển mặt đất và choáng toàn quân.'
  },

  boss_age2_dragon: {
    id: 'boss_age2_dragon',
    name: 'Royal Fire Drake',
    nameVi: 'Rồng Lửa Hoàng Gia',
    title: 'Hỏa Thần Trung Cổ',
    ageId: 2,
    hp: 8500,
    physicalArmor: 35,
    magicResistance: 30,
    tenacity: 0.40,
    hpRegen: 12.0,
    damage: 160,
    attackRange: 180,
    attackCooldown: 1.8,
    moveSpeed: 42,
    width: 160,
    height: 130,
    xpReward: 9000,
    killBounty: 1800,
    specialSkillId: 'SKILL_BOSS_FLAME_SWEEP_802',
    specialCooldown: 14,
    color: '#b91c1c',
    accentColor: '#f97316',
    projectileType: 'fireball',
    projectileSpeed: 420,
    aoeRadius: 80,
    descriptionVi: 'Rồng phun lửa thiêu rụi toàn tuyến với hơi thở rực cháy.'
  },

  boss_age3_juggernaut: {
    id: 'boss_age3_juggernaut',
    name: 'Steam Juggernaut Leviathan',
    nameVi: 'Siêu Thiết Giáp Hơi Nước Juggernaut',
    title: 'Pháo Đài Hơi Nước Công Nghiệp',
    ageId: 3,
    hp: 16500,
    physicalArmor: 50,
    magicResistance: 35,
    tenacity: 0.50,
    hpRegen: 18.0,
    damage: 280,
    attackRange: 220,
    attackCooldown: 2.2,
    moveSpeed: 30,
    width: 170,
    height: 140,
    xpReward: 25000,
    killBounty: 3500,
    specialSkillId: 'SKILL_BOSS_MORTAR_BARRAGE_803',
    specialCooldown: 16,
    color: '#78350f',
    accentColor: '#38bdf8',
    projectileType: 'grenade',
    projectileSpeed: 400,
    aoeRadius: 85,
    descriptionVi: 'Cỗ máy bọc thép công nghiệp khổng lồ nã pháo cối phá hủy đội hình.'
  },

  boss_age4_tank: {
    id: 'boss_age4_tank',
    name: 'Apocalypse Nuclear Tank',
    nameVi: 'Siêu Xe Tăng Hạt Nhân Apocalypse',
    title: 'Pháo Đài Di Động Chiến Trường',
    ageId: 4,
    hp: 32000,
    physicalArmor: 65,
    magicResistance: 45,
    tenacity: 0.60,
    hpRegen: 25.0,
    damage: 480,
    attackRange: 260,
    attackCooldown: 2.5,
    moveSpeed: 32,
    width: 180,
    height: 130,
    xpReward: 75000,
    killBounty: 8000,
    specialSkillId: 'SKILL_BOSS_MISSILE_SALVO_804',
    specialCooldown: 18,
    color: '#334155',
    accentColor: '#ef4444',
    projectileType: 'rocket',
    projectileSpeed: 480,
    aoeRadius: 90,
    descriptionVi: 'Xe tăng siêu trường siêu trọng trang bị bệ phóng tên lửa hủy diệt diện rộng.'
  },

  boss_age5_leviathan: {
    id: 'boss_age5_leviathan',
    name: 'Quantum God Leviathan',
    nameVi: 'Thần Máy Lượng Tử Leviathan',
    title: 'Kẻ Hủy Diệt Không Gian',
    ageId: 5,
    hp: 65000,
    physicalArmor: 75,
    magicResistance: 75,
    tenacity: 0.75,
    hpRegen: 40.0,
    damage: 850,
    attackRange: 320,
    attackCooldown: 2.0,
    moveSpeed: 36,
    width: 190,
    height: 160,
    xpReward: 250000,
    killBounty: 20000,
    specialSkillId: 'SKILL_BOSS_SINGULARITY_BEAM_805',
    specialCooldown: 20,
    color: '#0f172a',
    accentColor: '#c084fc',
    projectileType: 'plasma_bolt',
    projectileSpeed: 600,
    aoeRadius: 100,
    descriptionVi: 'Cỗ máy tối thượng với chùm tia tử thần xé rách không gian.'
  }
};
